In [6]:
import pandas as pd
import numpy as np

In [9]:
ecom_cust = pd.read_csv('E:/Data Analytics/Python/python practice/pandas/Customer.csv',header =0)

In [10]:
print(ecom_cust)

    Customer ID      Customer Name      Segment  Age        Country  \
0      CG-12520        Claire Gute     Consumer   67  United States
1      DV-13045    Darrin Van Huff    Corporate   31  United States
2      SO-20335     Sean O'Donnell     Consumer   65  United States
3      BH-11710    Brosina Hoffman     Consumer   20  United States
4      AA-10480       Andrew Allen     Consumer   50  United States
..          ...                ...          ...  ...            ...
788    CJ-11875       Carl Jackson    Corporate   64  United States
789    RS-19870         Roy Skaria  Home Office   39  United States
790    SC-20845         Sung Chung     Consumer   69  United States
791    RE-19405    Ricardo Emerson     Consumer   35  United States
792    SM-20905  Susan MacKendrick     Consumer   46  United States

                  City           State  Postal Code   Region
0            Henderson        Kentucky        42420    South
1          Los Angeles      California        90036     West
2      Fort Lauderdale         Florida        33311    South
3          Los Angeles      California        90032     West
4              Concord  North Carolina        28027    South
..                 ...             ...          ...      ...
788       Philadelphia    Pennsylvania        19140     East
789         Burlington            Iowa        52601  Central
790  Arlington Heights        Illinois        60004  Central
791               Kent            Ohio        44240     East
792             Newark            Ohio        43055     East

[793 rows x 9 columns]

In [11]:
ecom_cust.head

<bound method NDFrame.head of     Customer ID      Customer Name      Segment  Age        Country  \
0      CG-12520        Claire Gute     Consumer   67  United States
1      DV-13045    Darrin Van Huff    Corporate   31  United States
2      SO-20335     Sean O'Donnell     Consumer   65  United States
3      BH-11710    Brosina Hoffman     Consumer   20  United States
4      AA-10480       Andrew Allen     Consumer   50  United States
..          ...                ...          ...  ...            ...
788    CJ-11875       Carl Jackson    Corporate   64  United States
789    RS-19870         Roy Skaria  Home Office   39  United States
790    SC-20845         Sung Chung     Consumer   69  United States
791    RE-19405    Ricardo Emerson     Consumer   35  United States
792    SM-20905  Susan MacKendrick     Consumer   46  United States

                  City           State  Postal Code   Region
0            Henderson        Kentucky        42420    South
1          Los Angeles      California        90036     West
2      Fort Lauderdale         Florida        33311    South
3          Los Angeles      California        90032     West
4              Concord  North Carolina        28027    South
..                 ...             ...          ...      ...
788       Philadelphia    Pennsylvania        19140     East
789         Burlington            Iowa        52601  Central
790  Arlington Heights        Illinois        60004  Central
791               Kent            Ohio        44240     East
792             Newark            Ohio        43055     East

[793 rows x 9 columns]>

In [13]:
ecom_cust1 = pd.read_csv('E:/Data Analytics/Python/python practice/pandas/Customer.csv', index_col=0, header=0)

In [14]:
print(ecom_cust1)

                 Customer Name      Segment  Age        Country  \
Customer ID
CG-12520           Claire Gute     Consumer   67  United States
DV-13045       Darrin Van Huff    Corporate   31  United States
SO-20335        Sean O'Donnell     Consumer   65  United States
BH-11710       Brosina Hoffman     Consumer   20  United States
AA-10480          Andrew Allen     Consumer   50  United States
...                        ...          ...  ...            ...
CJ-11875          Carl Jackson    Corporate   64  United States
RS-19870            Roy Skaria  Home Office   39  United States
SC-20845            Sung Chung     Consumer   69  United States
RE-19405       Ricardo Emerson     Consumer   35  United States
SM-20905     Susan MacKendrick     Consumer   46  United States

                          City           State  Postal Code   Region
Customer ID
CG-12520             Henderson        Kentucky        42420    South
DV-13045           Los Angeles      California        90036     West
SO-20335       Fort Lauderdale         Florida        33311    South
BH-11710           Los Angeles      California        90032     West
AA-10480               Concord  North Carolina        28027    South
...                        ...             ...          ...      ...
CJ-11875          Philadelphia    Pennsylvania        19140     East
RS-19870            Burlington            Iowa        52601  Central
SC-20845     Arlington Heights        Illinois        60004  Central
RE-19405                  Kent            Ohio        44240     East
SM-20905                Newark            Ohio        43055     East

[793 rows x 8 columns]

In [16]:
ecom_cust1.describe()

              Age   Postal Code
count  793.000000    793.000000
mean    44.467844  55229.717528
std     15.526673  31679.223816
min     18.000000   1841.000000
25%     31.000000  27217.000000
50%     45.000000  55901.000000
75%     58.000000  90004.000000
max     70.000000  99207.000000

In [19]:
ecom_cust1.iloc[0:51]

,Customer Name,Segment,Age,Country,City,State,Postal Code,Region
Customer ID,,,,,,,,
CG-12520,Claire Gute,Consumer,67,United States,Henderson,Kentucky,42420,South
DV-13045,Darrin Van Huff,Corporate,31,United States,Los Angeles,California,90036,West
SO-20335,Sean O'Donnell,Consumer,65,United States,Fort Lauderdale,Florida,33311,South
BH-11710,Brosina Hoffman,Consumer,20,United States,Los Angeles,California,90032,West
AA-10480,Andrew Allen,Consumer,50,United States,Concord,North Carolina,28027,South
IM-15070,Irene Maddox,Consumer,66,United States,Seattle,Washington,98103,West
HP-14815,Harold Pawlan,Home Office,20,United States,Fort Worth,Texas,76106,Central
PK-19075,Pete Kriz,Consumer,46,United States,Madison,Wisconsin,53711,Central
AG-10270,Alejandro Grove,Consumer,18,United States,West Jordan,Utah,84084,West
ZD-21925,Zuschuss Donatelli,Consumer,66,United States,San Francisco,California,94109,West
KB-16585,Ken Black,Corporate,67,United States,Fremont,Nebraska,68025,Central
SF-20065,Sandra Flanagan,Consumer,41,United States,Philadelphia,Pennsylvania,19140,East
EB-13870,Emily Burns,Consumer,34,United States,Orem,Utah,84057,West
EH-13945,Eric Hoffmann,Consumer,21,United States,Los Angeles,California,90049,West
TB-21520,Tracy Blumstein,Consumer,48,United States,Philadelphia,Pennsylvania,19140,East
MA-17560,Matt Abelman,Home Office,19,United States,Houston,Texas,77095,Central
GH-14485,Gene Hale,Corporate,28,United States,Richardson,Texas,75080,Central
SN-20710,Steve Nguyen,Home Office,46,United States,Houston,Texas,77041,Central
LC-16930,Linda Cazamias,Corporate,31,United States,Naperville,Illinois,60540,Central
RA-19885,Ruben Ausman,Corporate,51,United States,Los Angeles,California,90049,West
ES-14080,Erin Smith,Corporate,20,United States,Melbourne,Florida,32935,South
ON-18715,Odella Nelson,Corporate,27,United States,Eagan,Minnesota,55122,Central
PO-18865,Patrick O'Donnell,Consumer,64,United States,Westland,Michigan,48185,Central
LH-16900,Lena Hernandez,Consumer,66,United States,Dover,Delaware,19901,East
DP-13000,Darren Powers,Consumer,40,United States,New Albany,Indiana,47150,Central
JM-15265,Janet Molinari,Corporate,23,United States,New York City,New York,10024,East
TB-21055,Ted Butterfield,Consumer,34,United States,Troy,New York,12180,East
KM-16720,Kunst Miller,Consumer,69,United States,Los Angeles,California,90004,West
PS-18970,Paul Stevenson,Home Office,31,United States,Chicago,Illinois,60610,Central
BS-11590,Brendan Sweed,Corporate,45,United States,Gilbert,Arizona,85234,West
KD-16270,Karen Daniels,Consumer,59,United States,Springfield,Virginia,22153,South
HM-14980,Henry MacAllister,Consumer,35,United States,New York City,New York,10009,East
JE-15745,Joel Eaton,Consumer,25,United States,Memphis,Tennessee,38109,South
KB-16600,Ken Brennan,Corporate,29,United States,Houston,Texas,77041,Central
SC-20770,Stewart Carmichael,Corporate,18,United States,Decatur,Alabama,35601,South
DN-13690,Duane Noonan,Consumer,42,United States,San Francisco,California,94122,West
JC-16105,Julie Creighton,Corporate,56,United States,Durham,North Carolina,27707,South
CS-12400,Christopher Schild,Home Office,33,United States,Chicago,Illinois,60623,Central
PG-18895,Paul Gonzalez,Consumer,64,United States,Rochester,Minnesota,55901,Central
GM-14455,Gary Mitchum,Home Office,64,United States,Houston,Texas,77095,Central
JS-15685,Jim Sink,Corporate,33,United States,Los Angeles,California,90036,West
KB-16315,Karl Braun,Consumer,70,United States,Minneapolis,Minnesota,55407,Central
RB-19705,Roger Barcio,Home Office,63,United States,Portland,Oregon,97206,West
PN-18775,Parhena Norris,Home Office,35,United States,New York City,New York,10009,East
KD-16345,Katherine Ducich,Consumer,33,United States,San Francisco,California,94122,West
ER-13855,Elpida Rittenbach,Corporate,56,United States,Saint Paul,Minnesota,55106,Central
RB-19465,Rick Bensley,Home Office,18,United States,Chicago,Illinois,60610,Central
GZ-14470,Gary Zandusky,Consumer,64,United States,Rochester,Minnesota,55901,Central
LC-16870,Lena Cacioppo,Consumer,63,United States,Aurora,Colorado,80013,West
JM-15250,Janet Martin,Consumer,62,United States,Charlotte,North Carolina,28205,South
PA-19060,Pete Armstrong,Home Office,31,United States,Orland Park,Illinois,60462,Central

In [21]:
ecom_cust1.iloc[0,5]

'Kentucky'

In [23]:
Puser = pd.DataFrame(
    [
        {"name": "anil",
        "age": 22
        },
        {
            "name": "shubham",
            "age": 23
        }
    ]
)

In [24]:
print(Puser)

      name  age
0     anil   22
1  shubham   23

In [25]:
Puser.to_csv('Puser.csv',index=0)

In [28]:
psection = [
    {
        'section':'sectionA',
        'numstud' : 24,
        'add' :'addA',
    },
    {
        'section' :'sectionB',
        'numstud' : 25,
        'add' : 'addB'
    }
    ]

In [30]:
pdsection = pd.DataFrame(psection)

In [31]:
pdsection

    section  numstud   add
0  sectionA       24  addA
1  sectionB       25  addB

In [32]:
pdsection.to_csv('pdsection.csv',index = 0)